language: php

php:
    - 7.0
    - 7.1

env:
    global:
        - TARGET=test
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: TARGET=cs_dry_run
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
        # test 3.4 LTS
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*
        # test the latest release (including beta releases)
        - php: 7.1
          env: DEPENDENCIES=beta

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ "$DEPENDENCIES" = "beta" ]; then perl -pi -e 's/^}$/,"minimum-stability":"beta"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
    - make $TARGET

branches:
  only:
    - master
