parameters:
    seo_override.fetchers_mapping: [] # Parameter configured in the DIC extension

services:
    seo_override.manager:
        class: Joli\SeoOverride\Bridge\Symfony\DataCollector\SeoManager
        arguments:
            - []
            - '%seo_override.domains%'
            - ~
            - '%seo_override.fetchers_mapping%'
        public: true

    seo_override.data_collector:
        class: Joli\SeoOverride\Bridge\Symfony\DataCollector\SeoOverrideDataCollector
        arguments:
            - '@seo_override.manager'
        tags:
            -
                name:     data_collector
                template: '@SeoOverride/data_collector/seo-override.html.twig'
                id:       'seo-override'
        public: false
