Joli\SeoOverride\Bridge\Doctrine\Entity\Seo:
    properties:
        title:
            - Length: { max: 255 }
        description:
            - Length: { max: 255 }
        keywords:
            - Length: { max: 255 }
        robots:
            - Length: { max: 255 }
        canonical:
            - Length: { max: 255 }
        ogTitle:
            - Length: { max: 255 }
        ogDescription:
            - Length: { max: 255 }
